name: Jedd & Mary's Wedding
favicon: null
layout_spectrum: 0.9822957736905664
typography_spectrum: 0.7336465914268047
title: Jedd & Mary's Wedding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8459296301007271
  lightness: 0.08080739411525428
  saturation: 0.9717860214877874
  rhythmicContrast: 0.05768545507453382
purpose: []
