name: Jedd & Mary's Wedding
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15081
title: Jedd & Mary's Wedding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7d5d3'
    - '#b0bd8d'
    - '#a28f49'
    - '#56410f'
    - '#5d7584'
  brandStrength: 0.8459296301007271
  lightness: 0.08080739411525428
  saturation: 0.9717860214877874
  rhythmicContrast: 0.05768545507453382
purpose: []
